# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_vote = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_vote.setGeometry(QtCore.QRect(100, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_vote.setFont(font)
        self.label_vote.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_vote.setObjectName("label_vote")
        self.label_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(70, 50, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.input_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.input_id.setObjectName("input_id")
        self.label_candidates = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_candidates.setGeometry(QtCore.QRect(100, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_candidates.setFont(font)
        self.label_candidates.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_candidates.setObjectName("label_candidates")
        self.radio_bianca = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_bianca.setGeometry(QtCore.QRect(120, 130, 62, 21))
        self.radio_bianca.setObjectName("radio_bianca")
        self.radio_group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_group.setObjectName("radio_group")
        self.radio_group.addButton(self.radio_bianca)
        self.radio_edward = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_edward.setGeometry(QtCore.QRect(120, 160, 62, 21))
        self.radio_edward.setObjectName("radio_edward")
        self.radio_group.addButton(self.radio_edward)
        self.radio_felicia = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_felicia.setGeometry(QtCore.QRect(120, 190, 62, 21))
        self.radio_felicia.setObjectName("radio_felicia")
        self.radio_group.addButton(self.radio_felicia)
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(110, 230, 81, 21))
        self.button_submit.setObjectName("button_submit")
        self.label_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(70, 250, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_result.setFont(font)
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting application"))
        self.label_vote.setText(_translate("MainWindow", "VOTE MENU"))
        self.label_id.setText(_translate("MainWindow", "ID"))
        self.label_candidates.setText(_translate("MainWindow", "CANDIDATES"))
        self.radio_bianca.setText(_translate("MainWindow", "Bianca"))
        self.radio_edward.setText(_translate("MainWindow", "Edward"))
        self.radio_felicia.setText(_translate("MainWindow", "Felicia"))
        self.button_submit.setText(_translate("MainWindow", "SUBMIT"))
        self.label_result.setText(_translate("MainWindow", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
